In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Read the CSV files into pandas DataFrames
books_all = pd.read_csv('/content/drive/MyDrive/Project/merged_emotions_all.csv')
books_kaggle = pd.read_csv('/content/drive/MyDrive/Project/Books.csv')

# Print columns of the first DataFrame
print("Columns of database_books_analyzed.csv:")
print(books_all.columns)

# Print columns of the second DataFrame
print("\nColumns of Books.csv:")
print(books_kaggle.columns)

# Print 10 entries from database_books_analyzed.csv
print("Entries from database_books_analyzed.csv:")
print(books_all.head(10))

# Print 10 entries from Books.csv
print("\nEntries from Books.csv:")
print(books_kaggle.head(10))

Columns of database_books_analyzed.csv:
Index(['Book', 'Author', 'Description', 'Genres', 'Year of Publication',
       'Publisher', 'URL', 'Aggregated Emotions', 'Aggregated Des Emotions'],
      dtype='object')

Columns of Books.csv:
Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')
Entries from database_books_analyzed.csv:
                                Book             Author  \
0                     my idea of fun          will self
1                 the magic mountain        thomas mann
2                       the drifters  james a. michener
3                the golden notebook      doris lessing
4  the missing piece meets the big o   shel silverstein
5                       'salem's lot       stephen king
6                      gerald's game       stephen king
7           i know this much is true         wally lamb
8             horton hatches the egg          dr. seuss
9               look homeward, angel       thomas wolfe

                                         Description   Genres  \
0  self established one brilliant daring inventiv...  Fiction
1  dizzyingly rich novel ideas mann uses sanatori...  Fiction
2  triumphant best seller james michener unfolds ...  Fiction
3  anna writer author one successful novel keeps ...  Fiction
4  shel silverstein celebrated author giving tree...  Fiction
5  librarian note alternate cover edition isbn 04...  Fiction
6  game husband wife game gerald game time jessie...  Fiction
7  afternoon october 12 1990 twin brother thomas ...  Fiction
8  beloved generations kindness loyalty horton el...  Fiction
9  look homeward angel story buried life 1929 nov...  Fiction

   Year of Publication                      Publisher  \
0                 1995                        Vintage
1                 1996                        Vintage
2                 1986                  Fawcett Books
3                 1981                         Bantam
4                 1981                  HarperCollins
5                 1990                    Signet Book
6                 2001                    Signet Book
7                 1999                    Regan Books
8                 1966  Random House Children's Books
9                 1995                       Scribner

                                                 URL  \
0  https://www.goodreads.com/book/show/119116.My_...
1  https://www.goodreads.com/book/show/88077.The_...
2  https://www.goodreads.com/book/show/42955.The_...
3  https://www.goodreads.com/book/show/24100.The_...
4  https://www.goodreads.com/book/show/30125.The_...
5  https://www.goodreads.com/book/show/11590._Sal...
6  https://www.goodreads.com/book/show/32692.Gera...
7  https://www.goodreads.com/book/show/227711.I_K...
8  https://www.goodreads.com/book/show/11301.Hort...
9  https://www.goodreads.com/book/show/12448.Look...

                                 Aggregated Emotions  \
0  [(' happy', 9), (' sad', 7), (' fearful', 6), ...
1  [(' happy', 32), (' attracted', 16), (' sad', ...
2  [(' happy', 18), (' free', 8), (' attracted', ...
3  [(' sad', 33), (' happy', 28), (' attracted', ...
4  [(' alone', 4), (' fearful', 1), (' attracted'...
5  [(' happy', 23), (' attached', 18), (' sad', 1...
6  [(' entitled', 14), (' fearful', 11), (' sad',...
7  [(' happy', 15), (' attracted', 11), (' attach...
8  [(' happy', 14), (' apathetic', 10), (' attach...
9  [(' happy', 29), (' lost', 19), (' sad', 14), ...

                             Aggregated Des Emotions
0  [(' average', 60), (' sad', 60), (' fearless',...
1                                                 []
2                                     [(' sad', 29)]
3                   [(' fearful', 60), (' sad', 30)]
4                                                 []
5                                 [(' fearful', 29)]
6     [(' sad', 56), (' alone', 56), (' angry', 28)]
7                                   [(' happy', 27)]
8                                   [(' happy', 30)]
9                                                 []

Entries from Books.csv:
         ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology
1  0002005018                                       Clara Callan
2  0060973129                               Decision in Normandy
3  0374157065  Flu: The Story of the Great Influenza Pandemic...
4  0393045218                             The Mummies of Urumchi
5  0399135782                             The Kitchen God's Wife
6  0425176428  What If?: The World's Foremost Military Histor...
7  0671870432                                    PLEADING GUILTY
8  0679425608  Under the Black Flag: The Romance and the Real...
9  074322678X            Where You'll Find Me: And Other Stories

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press
1  Richard Bruce Wright                2001       HarperFlamingo Canada
2          Carlo D'Este                1991             HarperPerennial
3      Gina Bari Kolata                1999        Farrar Straus Giroux
4       E. J. W. Barber                1999  W. W. Norton &amp; Company
5               Amy Tan                1991            Putnam Pub Group
6         Robert Cowley                2000    Berkley Publishing Group
7           Scott Turow                1993                  Audioworks
8       David Cordingly                1996                Random House
9           Ann Beattie                2002                    Scribner

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...
5  http://images.amazon.com/images/P/0399135782.0...
6  http://images.amazon.com/images/P/0425176428.0...
7  http://images.amazon.com/images/P/0671870432.0...
8  http://images.amazon.com/images/P/0679425608.0...
9  http://images.amazon.com/images/P/074322678X.0...

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...
5  http://images.amazon.com/images/P/0399135782.0...
6  http://images.amazon.com/images/P/0425176428.0...
7  http://images.amazon.com/images/P/0671870432.0...
8  http://images.amazon.com/images/P/0679425608.0...
9  http://images.amazon.com/images/P/074322678X.0...

                                         Image-URL-L
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...
5  http://images.amazon.com/images/P/0399135782.0...
6  http://images.amazon.com/images/P/0425176428.0...
7  http://images.amazon.com/images/P/0671870432.0...
8  http://images.amazon.com/images/P/0679425608.0...
9  http://images.amazon.com/images/P/074322678X.0...

<ipython-input-2-e5c3e978619e>:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_kaggle = pd.read_csv('/content/drive/MyDrive/Project/Books.csv')

In [ ]:
# Assuming 'books_all' and 'books_kaggle' are your DataFrames
# Convert the 'Book' column in 'books_all' to lowercase
books_all['Book'] = books_all['Book'].str.lower()

# Convert the 'Book-Title' column in 'books_kaggle' to lowercase
books_kaggle['Book-Title'] = books_kaggle['Book-Title'].str.lower()
# Merge the DataFrames based on the book title
merged_df = pd.merge(books_all, books_kaggle, left_on='Book', right_on='Book-Title', how='inner')

# Define the columns you want to include in the output
columns_to_print = ['Book', 'Author', 'ISBN', 'Book-Author' ]  # Add other column names as needed

# Print only the mentioned columns in the merged DataFrame
#print(merged_df[columns_to_print])

# Drop duplicate rows based on ISBN
merged_df_unique_isbn = merged_df.drop_duplicates(subset='Book')

# Print the resulting DataFrame
print(merged_df_unique_isbn[columns_to_print])

                                                   Book             Author  \
0                                        my idea of fun          will self
1                                    the magic mountain        thomas mann
3                                          the drifters  james a. michener
5                                   the golden notebook      doris lessing
9                     the missing piece meets the big o   shel silverstein
...                                                 ...                ...
4232                                           kon-tiki     thor heyerdahl
4235  touching the void: the true story of one man's...        joe simpson
4236  the old patagonian express: by train through t...       paul theroux
4237                                   the snow leopard  peter matthiessen
4238  winterdance: the fine madness of running the i...       gary paulsen

            ISBN        Book-Author
0     0679750932          WILL SELF
1     0679772871        THOMAS MANN
3     0449213536  James A. Michener
5     0553262106      DORIS LESSING
9     0060256575   Shel Silverstein
...          ...                ...
4232  0671499505     Thor Heyerdahl
4235  0060730552        Joe Simpson
4236  0395277884       Paul Theroux
4237  0140102663  Peter Matthiessen
4238  0156001454       Gary Paulsen

[1453 rows x 4 columns]

In [ ]:
merged_df_unique_isbn.to_csv('/content/drive/MyDrive/Project/all_books.csv')

In [ ]:
# Read the CSV files into pandas DataFrames
users_kaggle = pd.read_csv('/content/drive/MyDrive/Project/Users.csv')

# Print columns of the first DataFrame
print("Columns of Users.csv:")
print(users_kaggle.columns)

Columns of Users.csv:
Index(['User-ID', 'Location', 'Age'], dtype='object')

In [ ]:
# Read the CSV files into pandas DataFrames
ratings_kaggle = pd.read_csv('/content/drive/MyDrive/Project/Ratings.csv')

# Print columns of the first DataFrame
print("Columns of Users.csv:")
print(ratings_kaggle.columns)

Columns of Users.csv:
Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [ ]:
# Merge the DataFrames based on the book title
merged_all_books_ratings = pd.merge(merged_df_unique_isbn, ratings_kaggle, left_on='ISBN', right_on='ISBN', how='inner')

# Define the columns you want to include in the output
columns_to_print_new = ['Book', 'User-ID', 'Book-Rating', 'ISBN' ]  # Add other column names as needed

# Print the sorted DataFrame
print(merged_all_books_ratings[columns_to_print_new])

                                                    Book  User-ID  \
0                                         my idea of fun     4802
1                                         my idea of fun    23902
2                                         my idea of fun    59305
3                                         my idea of fun    59495
4                                         my idea of fun   128696
...                                                  ...      ...
46107  winterdance: the fine madness of running the i...   138761
46108  winterdance: the fine madness of running the i...   148199
46109  winterdance: the fine madness of running the i...   149031
46110  winterdance: the fine madness of running the i...   171118
46111  winterdance: the fine madness of running the i...   202324

       Book-Rating        ISBN
0                0  0679750932
1                7  0679750932
2                7  0679750932
3                0  0679750932
4                3  0679750932
...            ...         ...
46107            0  0156001454
46108            0  0156001454
46109            0  0156001454
46110            0  0156001454
46111            0  0156001454

[46112 rows x 4 columns]

In [ ]:
merged_all_books_ratings.to_csv('/content/drive/MyDrive/Project/all_ratings.csv')

In [ ]:
# Then, use the generated dictionaries to reindex UserID and MovieID in the data_df
user_list = merged_all_books_ratings['User-ID'].values
book_list = merged_all_books_ratings['ISBN'].values

print(user_list)
print(book_list)

user_list_size = len(user_list)
book_list_size = len(book_list)

print("Size of user_list:", user_list_size)
print("Size of movie_list:", book_list_size)


# Assuming user_list and movie_list are already defined
import numpy as np

unique_users = np.unique(user_list)
unique_books = np.unique(book_list)

print("Number of unique users:", len(unique_users))
print("Number of unique Books:", len(unique_books))

[  4802  23902  59305 ... 149031 171118 202324]
['0679750932' '0679750932' '0679750932' ... '0156001454' '0156001454'
 '0156001454']
Size of user_list: 46112
Size of movie_list: 46112
Number of unique users: 16795
Number of unique Books: 1453

In [ ]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [ ]:
books=books_kaggle = pd.read_csv('/content/drive/MyDrive/Project/Books.csv', low_memory=False)
ratings=pd.read_csv('/content/drive/MyDrive/Project/all_ratings.csv', low_memory=False)
users=pd.read_csv('/content/drive/MyDrive/Project/Users.csv', low_memory=False)

In [ ]:
len(ratings)

46112

In [ ]:
books_df=pd.read_csv('/content/drive/MyDrive/Project/Books.csv',low_memory=False)
ratings_df=pd.read_csv('/content/drive/MyDrive/Project/all_ratings.csv',low_memory=False)
users_df=pd.read_csv('/content/drive/MyDrive/Project/Users.csv',low_memory=False)

In [ ]:
ratings

,Unnamed: 0,Book,Author,Description,Genres,Year of Publication,Publisher_x,URL,Aggregated Emotions,Aggregated Des Emotions,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher_y,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",0679750932,my idea of fun,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,4802,0
1,1,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",0679750932,my idea of fun,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,23902,7
2,2,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",0679750932,my idea of fun,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,59305,7
3,3,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",0679750932,my idea of fun,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,59495,0
4,4,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",0679750932,my idea of fun,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,128696,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46107,46107,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],0156001454,winterdance: the fine madness of running the i...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,138761,0
46108,46108,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],0156001454,winterdance: the fine madness of running the i...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,148199,0
46109,46109,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],0156001454,winterdance: the fine madness of running the i...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,149031,0
46110,46110,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],0156001454,winterdance: the fine madness of running the i...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,171118,0
46111,46111,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],0156001454,winterdance: the fine madness of running the i...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,202324,0

In [ ]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [ ]:
ratings.isnull().sum()

Unnamed: 0                 0
Book                       0
Author                     0
Description                0
Genres                     0
Year of Publication        0
Publisher_x                0
URL                        0
Aggregated Emotions        0
Aggregated Des Emotions    0
ISBN                       0
Book-Title                 0
Book-Author                0
Year-Of-Publication        0
Publisher_y                0
Image-URL-S                0
Image-URL-M                0
Image-URL-L                0
User-ID                    0
Book-Rating                0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoders for user and item IDs
user_encoder = LabelEncoder()
item_encoder = LabelEncoder()

# Fit and transform user and item IDs
ratings['user_id'] = user_encoder.fit_transform(ratings['User-ID'])
ratings['item_id'] = item_encoder.fit_transform(ratings['ISBN'])


# Fit and transform user and item IDs
ratings_df['user_id'] = user_encoder.fit_transform(ratings_df['User-ID'])
ratings_df['item_id'] = item_encoder.fit_transform(ratings_df['ISBN'])

In [ ]:
ratings

,Unnamed: 0,Book,Author,Description,Genres,Year of Publication,Publisher_x,URL,Aggregated Emotions,Aggregated Des Emotions,...,Book-Author,Year-Of-Publication,Publisher_y,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating,user_id,item_id
0,0,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",...,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,4802,0,302,1063
1,1,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",...,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,23902,7,1445,1063
2,2,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",...,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,59305,7,3651,1063
3,3,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",...,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,59495,0,3665,1063
4,4,my idea of fun,will self,self established one brilliant daring inventiv...,Fiction,1995,Vintage,https://www.goodreads.com/book/show/119116.My_...,"[(' happy', 9), (' sad', 7), (' fearful', 6), ...","[(' average', 60), (' sad', 60), (' fearless',...",...,WILL SELF,1995,Vintage,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,http://images.amazon.com/images/P/0679750932.0...,128696,3,7878,1063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46107,46107,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,138761,0,8487,214
46108,46108,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,148199,0,9085,214
46109,46109,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,149031,0,9130,214
46110,46110,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,171118,0,10385,214
46111,46111,winterdance: the fine madness of running the i...,gary paulsen,fueled passion running dogs gary paulsen enter...,Adventure,1995,Harvest Books,https://www.goodreads.com/book/show/2923.Winte...,"[(' happy', 22), (' attracted', 12), (' attach...",[],...,Gary Paulsen,1995,Harvest Books,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,http://images.amazon.com/images/P/0156001454.0...,202324,0,12094,214

In [ ]:
ratings_train = ratings[0:36890]
ratings_test = ratings[36890:].reset_index(drop=True)

In [ ]:
class RatingDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return {
            'user_id': self.data['user_id'][idx],
            'book_id': self.data['item_id'][idx],
            'rating': self.data['Book-Rating'][idx]
        }

In [ ]:
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split

# Instantiate train and test datasets
train_dataset = RatingDataset(ratings_train)
test_dataset = RatingDataset(ratings_test)

# Create train and test loaders
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# dataset = RatingDataset(ratings)
# dataloader = DataLoader(dataset, batch_size=64, shuffle=True)

In [ ]:
print(len(train_dataset))
print(len(train_loader))

36890
577

In [ ]:
class GMF(nn.Module):
    def __init__(self, num_users, num_items, embedding_size):
        super(GMF, self).__init__()
        self.relu = nn.ReLU()
        self.user_embedding = nn.Embedding(num_users, embedding_size)
        self.item_embedding = nn.Embedding(num_items, embedding_size)
        self.fc = nn.Linear(embedding_size, 32)
        self.output_layer = nn.Linear(32, 1)
        self.dropout = nn.Dropout(0.2)

    def forward(self, user_ids, item_ids):
        user_embed = self.user_embedding(user_ids)
        item_embed = self.item_embedding(item_ids)
        element_product = user_embed * item_embed
        x = self.fc(element_product)
        x = self.relu(x)
        x = self.dropout(x)
        output = self.output_layer(x)
        output = torch.sigmoid(output)  # Ensure output is between 0 and 1
        return output.view(-1)

In [ ]:
class MLP(nn.Module):
    def __init__(self, num_users, num_items, embedding_size, hidden_layers=[64, 32]):
        super(MLP, self).__init__()
        self.user_embedding = nn.Embedding(num_users, embedding_size)
        self.item_embedding = nn.Embedding(num_items, embedding_size)
        layers = []
        input_size = embedding_size * 2
        for hidden_size in hidden_layers:
            layers.append(nn.Linear(input_size, hidden_size))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(0.2))
            input_size = hidden_size
        layers.append(nn.Linear(hidden_layers[-1], 1))
        self.layers = nn.Sequential(*layers)

    def forward(self, user_ids, item_ids):
        user_embed = self.user_embedding(user_ids)
        item_embed = self.item_embedding(item_ids)
        concat_embed = torch.cat((user_embed, item_embed), dim=1)
        output = self.layers(concat_embed)
        output = torch.sigmoid(output)  # Ensure output is between 0 and 1
        return output.view(-1)

In [ ]:
class NCF(nn.Module):
    def __init__(self, gmf_model, mlp_model):
        super(NCF, self).__init__()
        self.gmf = gmf_model
        self.mlp = mlp_model

    def forward(self, user_ids, item_ids):
        gmf_output = self.gmf(user_ids, item_ids)
        mlp_output = self.mlp(user_ids, item_ids)
        combined_output = (gmf_output + mlp_output) / 2
        return combined_output

In [ ]:
num_users = len(ratings['User-ID'].unique())
num_items = len(ratings['ISBN'].unique())
embedding_size = 64
hidden_layers = [128, 64, 32]

In [ ]:
print(num_users)
print(num_items)

16795
1453

In [ ]:
# Initialize GMF model
gmf_model = GMF(num_users, num_items, embedding_size).to(device)

# Initialize MLP model
mlp_model = MLP(num_users, num_items, embedding_size, hidden_layers).to(device)

In [ ]:
#Loss criterion for GMF and MLP models
models_criterion = nn.MSELoss()

# Optimizer for GMF model
gmf_optimizer = optim.Adam(gmf_model.parameters(), lr=0.001)

# Optimizer for MLP model
mlp_optimizer = optim.Adam(mlp_model.parameters(), lr=0.001)

In [ ]:
def train_gmf(model, dataloader, criterion, optimizer, num_epochs):
    for epoch in range(num_epochs):
        total_loss = 0.0
        i=0
        total_diff=0
        total_len=0
        for batch in dataloader:
            user_ids = batch['user_id'].to(device)
            item_ids = batch['book_id'].to(device)
            ratings = batch['rating'].to(device)

            optimizer.zero_grad()
            predictions = model(user_ids, item_ids)
            loss = criterion(predictions, (ratings.float()/10) )
            loss.backward()
            optimizer.step()

            if (i % 1000 == 0):
                actual_ratings = 10*predictions
                diff = torch.abs( actual_ratings - ratings ).sum().item()
                print(f'Batch [{i+1}/{len(dataloader)}], Loss: {loss.item()}, Avg. Diff: { (diff/len(ratings)) }')

            i = i + 1

            total_loss += loss.item()

        print(f'GMF Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss / len(dataloader)}')

In [ ]:
def train_mlp(model, dataloader, criterion, optimizer, num_epochs):
    for epoch in range(num_epochs):
        total_loss = 0.0
        i=0
        for batch in dataloader:
            user_ids = batch['user_id'].to(device)
            item_ids = batch['book_id'].to(device)
            ratings = batch['rating'].to(device)

            optimizer.zero_grad()
            predictions = model(user_ids, item_ids)
            loss = criterion(predictions, (ratings.float()/10))
            loss.backward()
            optimizer.step()

            if (i % 1000 == 0):
                actual_ratings = 10*predictions
                diff = torch.abs( actual_ratings - ratings ).sum().item()
                print(f'Batch [{i+1}/{len(dataloader)}], Loss: {loss.item()}, Avg. Diff: { (diff/len(ratings)) }')

            i = i + 1

            total_loss += loss.item()

        print(f'MLP Epoch [{epoch+1}/{num_epochs}], Loss: {total_loss / len(dataloader)}')

In [ ]:
num_epochs = 5

print("Training GMF...")
train_gmf(gmf_model, train_loader, models_criterion, gmf_optimizer, num_epochs)

print("Training MLP...")
train_mlp(mlp_model, train_loader, models_criterion, mlp_optimizer, num_epochs)

Training GMF...
Batch [1/577], Loss: 0.17991478741168976, Avg. Diff: 3.990741014480591
GMF Epoch [1/5], Loss: 0.1676479492278405
Batch [1/577], Loss: 0.1619666963815689, Avg. Diff: 3.6908278465270996
GMF Epoch [2/5], Loss: 0.16172736020600567
Batch [1/577], Loss: 0.1750924289226532, Avg. Diff: 3.9132213592529297
GMF Epoch [3/5], Loss: 0.1578188497876584
Batch [1/577], Loss: 0.13785244524478912, Avg. Diff: 3.5347824096679688
GMF Epoch [4/5], Loss: 0.1518688659785732
Batch [1/577], Loss: 0.14531365036964417, Avg. Diff: 3.6497743129730225
GMF Epoch [5/5], Loss: 0.14262760721108322
Training MLP...
Batch [1/577], Loss: 0.17538931965827942, Avg. Diff: 3.9506139755249023
MLP Epoch [1/5], Loss: 0.16163885750948245
Batch [1/577], Loss: 0.16742625832557678, Avg. Diff: 3.8899731636047363
MLP Epoch [2/5], Loss: 0.15135627341952232
Batch [1/577], Loss: 0.14261837303638458, Avg. Diff: 3.47813081741333
MLP Epoch [3/5], Loss: 0.13804381866285664
Batch [1/577], Loss: 0.10661862045526505, Avg. Diff: 2.809652090072632
MLP Epoch [4/5], Loss: 0.12536606981549767
Batch [1/577], Loss: 0.13030724227428436, Avg. Diff: 3.1169369220733643
MLP Epoch [5/5], Loss: 0.11390701304327057

In [ ]:
model = NCF(gmf_model, mlp_model)

In [ ]:
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [ ]:
import math

In [ ]:
num_epochs = 10
for epoch in range(num_epochs):
    i=0
    for batch in train_loader:
        user_ids = batch['user_id'].to(device)
        item_ids = batch['book_id'].to(device)
        ratings = batch['rating'].to(device)

        optimizer.zero_grad()
        predictions = model(user_ids, item_ids)
        loss = criterion(predictions, (ratings.float()/10))
        loss.backward()
        optimizer.step()

        if (i % 1000 == 0):
            actual_ratings = 10*predictions
            rmse = math.sqrt(torch.square(actual_ratings-ratings).sum().item()/len(ratings))
            diff = torch.abs( actual_ratings - ratings ).sum().item()
            print(f'Batch [{i+1}/{len(train_loader)}], Loss: {loss.item()}, Avg. Diff: { (diff/len(ratings)) }, RMSE: {rmse}')


        i = i + 1


    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Batch [1/577], Loss: 0.10345868766307831, Avg. Diff: 2.830606460571289, RMSE: 3.216499653039834
Epoch [1/10], Loss: 0.07590187340974808
Batch [1/577], Loss: 0.08035969734191895, Avg. Diff: 2.3166513442993164, RMSE: 2.834778604087433
Epoch [2/10], Loss: 0.06812019646167755
Batch [1/577], Loss: 0.08267353475093842, Avg. Diff: 2.2874062061309814, RMSE: 2.87530068193496
Epoch [3/10], Loss: 0.06490980833768845
Batch [1/577], Loss: 0.05436505377292633, Avg. Diff: 1.6913323402404785, RMSE: 2.331631471242398
Epoch [4/10], Loss: 0.05112120136618614
Batch [1/577], Loss: 0.06103706359863281, Avg. Diff: 1.8225985765457153, RMSE: 2.4705680237271914
Epoch [5/10], Loss: 0.04777903854846954
Batch [1/577], Loss: 0.058937907218933105, Avg. Diff: 1.7453290224075317, RMSE: 2.427713162367101
Epoch [6/10], Loss: 0.05064346268773079
Batch [1/577], Loss: 0.03438897058367729, Avg. Diff: 1.1895307302474976, RMSE: 1.8544264264974533
Epoch [7/10], Loss: 0.06541459262371063
Batch [1/577], Loss: 0.034766413271427155, Avg. Diff: 1.2297464609146118, RMSE: 1.8645752705944925
Epoch [8/10], Loss: 0.06733594834804535
Batch [1/577], Loss: 0.04205438867211342, Avg. Diff: 1.2736318111419678, RMSE: 2.0507166098443737
Epoch [9/10], Loss: 0.03608434647321701
Batch [1/577], Loss: 0.023707782849669456, Avg. Diff: 0.9371012449264526, RMSE: 1.5397331209665102
Epoch [10/10], Loss: 0.028554240241646767

In [ ]:
model.eval()

total_loss = 0
total_diff = 0
total_examples = 0
total_squared_error = 0

with torch.no_grad():
    for batch in test_loader:
        user_ids = batch['user_id'].to(device)
        item_ids = batch['book_id'].to(device)
        ratings = batch['rating'].to(device)

        predictions = model(user_ids, item_ids)
        loss = criterion(predictions, (ratings.float() / 10))

        actual_ratings = 10 * predictions
        diff = torch.abs(actual_ratings - ratings).sum().item()

        total_loss += loss.item() * len(ratings)
        total_diff += diff
        total_examples += len(ratings)
        total_squared_error += torch.square(actual_ratings-ratings).sum().item()

avg_loss = total_loss / total_examples
avg_diff = total_diff / total_examples
rmse = math.sqrt(total_squared_error / total_examples)

print('Evalution Measures:')
print(f'Evaluation Loss: {avg_loss}, Average Difference: {avg_diff}, RMSE: {rmse}')

Evalution Measures:
Evaluation Loss: 0.19048026339838703, Average Difference: 3.47972325093574, RMSE: 4.364404511016488

In [ ]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
users[users['User-ID'] == 276704]

        User-ID                Location  Age
276703   276704  cedar park, texas, usa  NaN

In [ ]:
book_ratings = ratings_df.groupby('item_id')['Book-Rating'].mean().reset_index()
book_ratings = book_ratings.sort_values(by='Book-Rating', ascending=False)
top_64_books = book_ratings.head(64)
print(top_64_books)

      item_id  Book-Rating
539       539    10.000000
626       626    10.000000
950       950    10.000000
1290     1290    10.000000
816       816    10.000000
...       ...          ...
1442     1442     8.600000
1342     1342     8.600000
1005     1005     8.500000
746       746     8.500000
1           1     8.333333

[64 rows x 2 columns]

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu

In [ ]:
user_id = 276704
user_id_tensor = torch.LongTensor([user_id] * 64).to(device)

top_64_books = top_64_books['item_id'].tolist()
item_ids_tensor = torch.LongTensor(top_64_books).to(device)

print("User ID Tensor:", user_id_tensor)
print("Top 10 Books Tensor:", item_ids_tensor)

User ID Tensor: tensor([276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704, 276704,
        276704])
Top 10 Books Tensor: tensor([ 539,  626,  950, 1290,  816,  769,  500, 1035, 1405,  189, 1146,  762,
         524,   43, 1304, 1150,  380,  786,  794,  818, 1121,  208, 1363,  472,
        1450, 1248, 1222,    9,  251,  439,  464,  334, 1250,  946, 1321,  184,
        1175,  558,  508, 1428,  803, 1369,  920,  563,  534,  304, 1327, 1254,
        1119,  735,  909, 1247, 1134, 1416,  483,  368,  905, 1225, 1297, 1442,
        1342, 1005,  746,    1])

In [ ]:


# Clip user indices to valid range
user_id_tensor = torch.clip(user_id_tensor, 0, num_users - 1)

# Clip item indices to valid range
item_ids_tensor = torch.clip(item_ids_tensor, 0, num_items - 1)

# Now, you can use user_id_tensor and item_ids_tensor in your model
# predictions = model(user_id_tensor, item_ids_tensor)


print(user_id_tensor)
print(item_ids_tensor)
predictions = model(user_id_tensor, item_ids_tensor)

indexed_predictions = [(idx, pred) for idx, pred in enumerate(predictions)]

# Sort the indexed predictions by the prediction values in descending order
sorted_predictions = sorted(indexed_predictions, key=lambda x: x[1], reverse=True)

# Get the top 3 indices
top_3_indices = [idx for idx, _ in sorted_predictions[:3]]

# Get the top 3 book ISBNs
top_3_book_isbns = [item_ids_tensor[idx].item() for idx in top_3_indices]

print("Top 3 Book ISBNs:", top_3_book_isbns)

tensor([16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794, 16794,
        16794, 16794, 16794, 16794])
tensor([ 539,  626,  950, 1290,  816,  769,  500, 1035, 1405,  189, 1146,  762,
         524,   43, 1304, 1150,  380,  786,  794,  818, 1121,  208, 1363,  472,
        1450, 1248, 1222,    9,  251,  439,  464,  334, 1250,  946, 1321,  184,
        1175,  558,  508, 1428,  803, 1369,  920,  563,  534,  304, 1327, 1254,
        1119,  735,  909, 1247, 1134, 1416,  483,  368,  905, 1225, 1297, 1442,
        1342, 1005,  746,    1])
Top 3 Book ISBNs: [1005, 483, 464]